[lint]
select = ["E", "F", "W", "I", "N", "UP", "B", "C4", "SIM", "T20"]
ignore = ["E501", "B008"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]

[format]
quote-style = "double"
indent-style = "space"
